### ISSUE TITLE
Remove AngularUtils 

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#10]
AngularUtils is no longer maintained.
Move to a more standard pagination and remove AngularUtils.
https://github.com/openbmc/phosphor-webui/blob/10ed37600bc682cf448a1084d73d53accb16cb6d/app/server-health/controllers/log-controller.html#L73

https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-pagination-controls

**Comment by BeccaBroek** [comment]
The only more standard way to paginate without writing our own pagination directive, I think, would be https://angular-ui.github.io/bootstrap/ and this is also no longer maintained. There are projects that are maintained which can be used for pagination, but they all seem to require Angular 2+ and currently we are using 1.7. I don't think it would be worth the effort to create our own, as it would look a lot like AngularUtil's implementation and think that switching the way we do pagination would maybe make more sense in the future if we start using Angular 2 or higher.

Two Angular 2+ options:
https://github.com/michaelbromley/ngx-pagination
https://ng-bootstrap.github.io/#/home

**Comment by BeccaBroek** [comment]
See
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/16421/
