### ISSUE TITLE
Logging is not possible due to connect-src settings.

### ISSUE THREAD

**Issue by zkurzyns** [openbmc/phosphor-webui#100]
When developing phosphor-webui locally with qemu it is not possible to login into bmcweb.

Each attempt ends with message
`Content Security Policy: The page’s settings blocked the loading of a resource at https://127.0.0.1/login (“connect-src”).`

Workaround is to replace **connect-src** settings in file webpack.config.js with this:
`connect-src': ['*']`

**Comment by edtanous** [comment]
It's actually been on my list to completely delete the webpack CSP section.  It's duplicated functionality with bmcweb, and unnecessary no have in webpack.

**Comment by zkurzyns** [comment]
Closing this, it seems to be fixed with commit f6387628d22b525c20a16e4b928ceece0e03c92b
