### ISSUE TITLE
LDAP setup initially gives a "fake" error message

### ISSUE THREAD

**Issue by lpanayioto** [openbmc/phosphor-webui#102]
LDAP setup will always give an error the first time you click save. Although if it is correct it will save the settings.

**Unexpected behavior you saw**
After correctly entering the LDAP settings and clicking save for the first time I got an error message. Settings were still saved after refreshing. All subsequent messages will be correct.

**Expected behavior**
Success Message when correctly entering the LDAP settings even on the first click.

**To Reproduce**

1. Navigate to LDAP settings Access Control -> LDAP

2. Enable LDAP authentication & Open LDAP and enter LDAP settings below

3. Save Settings

4. Click Reset

5. Enter Bind Password again and Save Settings

**OpenBMC Information:**

- /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.8.0-dev"
VERSION_ID="2.8.0-dev-913-g3d2621456"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.8.0-dev"
BUILD_ID="2.8.0-dev"
OPENBMC_TARGET_MACHINE="s2600wf"
- uname -a:
Linux s2600wf 5.3.11-d41fa1f #1 Mon Nov 25 22:35:07 UTC 2019 armv6l GNU/Linux

**Comment by geissonator** [comment]
@gtmills or @gkeishin any known issues in this area?

**Comment by gtmills** [comment]
I have not. @derick-montague

**Comment by derick-montague** [comment]
I am able to reproduce this. Has anything changed on the backend because this was working? The request is returning a 400 with the following message:

> The value null for the property AuthenticationType is of a different type than the property can accept
