### ISSUE TITLE
How to send CTRL-ALT-DEL (or other special key combinations)?

### ISSUE THREAD

**Issue by MaxPower2005** [openbmc/phosphor-webui#106]
The IP KVM panel of phosphor-webui seems to be missing a feature to send special code sequences like CTRL-ALT-DEL (CAD) to the target. Some of the special key combination needed in daily life seem to be filtered out either by the OS or the browser. CAD for example is essential to activate the login process on all versions of Windows Server.

**Comment by gtmills** [comment]
Thought we supported CTRL+ALT+DEL. 
https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/directives/kvm-console.js#L29

Maybe it isn't working.
Could you add some debug statements in there?

**Comment by MaxPower2005** [comment]
Hi
I noticed that webui-vue is offering a "Send Ctrl+Alt+Delete" link on the upper edge of the KVM screen.
Therefore problem solved.
