### ISSUE TITLE
Login redirect doesn't verify redirect is local

### ISSUE THREAD

**Issue by feistjj** [openbmc/phosphor-webui#109]
https://github.com/openbmc/phosphor-webui/blob/c652ed1889599da3ca2a0e0d36979e099f9b3b8c/app/login/controllers/login-controller.js#L46

This can be used to redirect a user anywhere given a bad link, should check first that redirect is local to current host.

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/29216
