### ISSUE TITLE
The "operations" section in Server Power operations menu has moved to the bottom of the page

### ISSUE THREAD

**Issue by adathatri** [openbmc/phosphor-webui#112]
The 'Operations' section has moved to the bottom of the page in 'Server power operations' page. This  used to be next to 'Host OS boot settings'.

![image](https://user-images.githubusercontent.com/47553162/83627753-10ef4000-a5b5-11ea-8e67-b9cffda379ad.png)

Build info:
VERSION="2.9.0-dev"
VERSION_ID=2.9.0-dev-120-g31e5d7989
OPENBMC_TARGET_MACHINE="witherspoon"

**Comment by nest1ing** [comment]
I confirm.
The issue is reproduced on our Vegman hardware too with the latest WebUI version.

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/33476 should resolve
