### ISSUE TITLE
SOL console in webui stops outputting during petitboot

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-webui#13]
```
[w54]# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v2.3-163"
VERSION_ID="v2.3-163-g8f3fc97"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v2.3-163"
BUILD_ID="v2.3"
```

Using latest chrome on my macbook.

Using the SOL console in the GUI, I see the hostboot isteps fine, then most of petitboot, then it suddenly just stops, here's the last of what I get.

[   69.352195504,5] PHB#0004:01:00.4 [EP  ] 10b5 87d0 R:ca C:088000 (system-peripheral) 
[   69.352243104,5] PHB#0005:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:01..01 
[   69.352288786,5] PHB#0005:01:00.0 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) 
[   69.352340102,5] PHB#0005:01:00.1 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) 
[   69.352390040,5] PHB#0006:00:00.0 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352440204,5] PHB#0006:00:00.1 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352482785,5] PHB#0006:00:01.0 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352527499,5] PHB#0006:00:01.1 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352571771,5] PHB#0006:00:02.0 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352620737,5] PHB#0006:00:02.1 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352668622,5] PHB#0007:00:00.0 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
[   69.352717447,5] PHB#0007:00:00.1 [EP  ] 1014 04ea R:01 C:060400 (           pci) 
<a bunch of blank lines>

Hitting enter does nothing, but if I hit the "Refresh" button in the upper right and then hit enter in the console then I'll get my OS login:

w54l login: 
Red Hat Enterprise Linux Server 7.4 (Maipo)
Kernel 4.14.0-49.el7a.ppc64le on an ppc64le

**Comment by geissonator** [comment]
If I hit the refresh button quickly then I can catch petitboot, and it seems to capture my inputs fine, but it doesn't seem to process my command "exit" for some reason from the debug shell.  Same type of hang and refresh is needed.

**Comment by BeccaBroek** [comment]
I'm seeing the websocket connection to console0 close consistently during boot on the SOL console page with error code 1006, causing the console to stop outputting messages. 

On refresh, the websocket re opens and the SOL console begins outputting again, but will close again. Not sure what is causing the closure, the error code 1006 meaning "that a connection was closed abnormally"
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Properties

First closure
<img width="1481" alt="screen shot 2018-09-13 at 3 40 34 pm" src="https://user-images.githubusercontent.com/26717697/45514669-9987d600-b76b-11e8-80a1-5e8d43646240.png">

Second closure
<img width="1538" alt="screen shot 2018-09-13 at 3 41 11 pm" src="https://user-images.githubusercontent.com/26717697/45514691-ae646980-b76b-11e8-8828-3295f1944133.png">

**Comment by BeccaBroek** [comment]
@geissonator , returned to looking at this yesterday and was unable to recreate it with latest master. Wondering if you want to confirm?

**Comment by edtanous** [comment]
Any update here?

**Comment by BeccaBroek** [comment]
Looked at this again this morning on latest master on one of our pool machines and still do not see the websocket closing.  I can't say that I know why it was happening (I was originally able to recreate), but I can't recreate it now.

**Comment by geissonator** [comment]
Sounds like we're good to go here now.
