### ISSUE TITLE
Implement additional capabilities that are missing from current GUI (e.g. add/remove IPV4 addresses, read-only view of addresses obtained from dhcp)

### ISSUE THREAD

**Issue by alissaylee** [openbmc/phosphor-webui#15]
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318318937_Network_Assign_new_static_IP
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318318936_Network_Assign_Existing_static_IP

**Initial setup of Static IP address:**
- IPV4 addresses may or may not be available in the GUI
- Add/remove IPV4 address
- Add/remove DNS server
- Test IP address connectivity for dns servers (before saving)
- Field validation of DNS server connectivity after saving settings
- Field validation for required fields (i.e. IPV4, Gateway and Netmask Length)
- If user adds an IPV4 address or DNS server and continues to save settings (while input fields are empty), page will discard those fields (for IPV4, all 3 fields per row would need to be empty to be removed after saving)

--------------------------------------------------------------------------------------------------
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318318928_Network_Save_Settings
- Secondary confirmation pop-up message will appear upon selecting to save settings.

--------------------------------------------------------------------------------------------------
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318318924_Network_Save_Settings_Successful
- Successful/Failed toast messages will appear on the top right corner of page
- Notifications will inform user is settings saved successfully or failed (GUI will not save input fields with errors)

**Comment by derick-montague** [comment]
@gtmills @jandraa - All the InVision links in this issue reference a project that has been archived. Is this issue still valid?

**Comment by gtmills** [comment]
This is covered by https://github.com/openbmc/phosphor-webui/issues/62, Closing.
