### ISSUE TITLE
security: do not autocomplete username and password fields

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/phosphor-webui#18]
The web application should not autocomplete username and password fields.  It may apply to other fields.  See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by gtmills** [comment]
@joseph-reynolds Why is having autocomplete fields a security concern?

**Comment by edtanous** [comment]
Because security scanners list it as a medium priority issue, and someone could use it to compromise a bmc with a password saved on a compromised computer.  It's been on my list of things to fix for a while now.

**Comment by joseph-reynolds** [comment]
The username+password grants privileged access to resources, so they must be protected.  Generally speaking, for higher security applications, you should not store the username or password for any longer than is needed.  So there should be a way to instruct the browser to not store them as autocomplete data.

**Comment by joseph-reynolds** [comment]
This fix looks good. The scanner is still complaining about a form with class="user-manage__form" which has fields for changing passwords.  We ought to apply the fix to those fields as well.
