### ISSUE TITLE
web service not handling missing inventory

### ISSUE THREAD

**Issue by causten** [openbmc/phosphor-webui#2]
After attempting to login in I get kicked back out to the login page.  I see lots of 200 calls but hit two 404s when attempting to collect inventory on a part that does not exist yet.  I believe the 
`xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet`  does not exist until the system has booted.  Honestly that in itself seems like a bug since it is the inventory pat of the BMC itself, however the web code cant simply exit out.  It needs to gracefully handle missing parts.  How else could we update the firmware for a web bug in the field.

```
xxx - - [30/Sep/2017:00:04:46 +0000] "GET /xyz/openbmc_project/led/groups/enclosure_identify HTTP/1.1" 200 80 "https://xxx/web/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
xxx - - [30/Sep/2017:00:04:47 +0000] "GET /xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet HTTP/1.1" 404 240 "https://xxx/web/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
xxx - - [30/Sep/2017:00:04:47 +0000] "GET /xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc HTTP/1.1" 404 231 "https://xxx/web/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0"
```

**Comment by gtmills** [comment]
This is fixed now. Closing. Remove the functions that call `/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc` and `/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet` here:
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/11965/. They were unused.
