### ISSUE TITLE
Event log: Date formats on event log page should match

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#21]
![event_page](https://user-images.githubusercontent.com/5455127/46626164-1c4a4980-cafc-11e8-8195-4cb747d7539c.PNG)

**Comment by gtmills** [comment]
Overview page would also have the same problem

**Comment by BeccaBroek** [comment]
We've discussed and I will implement so that the formats are consistent with the exception that the event logs will display the timezone following. There will be no change to the format at the top of the page.
(Oct 10, 2018 12:19:23 PM EDT)
