### ISSUE TITLE
Change text color of "Functional firmware version"

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#22]
Blue is used to imply clickable links.. 
![functional_firmware_version](https://user-images.githubusercontent.com/5455127/46626821-1b1a1c00-cafe-11e8-92f7-a9a983d603dc.PNG)
The IBM design team made this recommendation:

Visual treatment of the “Functional firmware version” implies a
clickable state when in actuality it is not. This is in opposition to the
same blue color treatment used in the UI as a call to action.
• Recommendation: Use the color #666666 for the firmware version text.

**Comment by BeccaBroek** [comment]
<img width="1114" alt="screen shot 2018-10-10 at 3 50 10 pm" src="https://user-images.githubusercontent.com/26717697/46765283-39218100-cca4-11e8-8e7a-ade6b84debb1.png">
With change, will look like this
