### ISSUE TITLE
Firmware page: Move the "more info" icon

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#23]
![firmware_more_icon](https://user-images.githubusercontent.com/5455127/46627528-53225e80-cb00-11e8-9bae-82eb908400e7.PNG)

The IBM design team made the following recommendation: 
Location of “more info” icon appears irrelevant to the version level.
• Recommendation: Icon is placed 20px to the right of the version level.

**Comment by BeccaBroek** [comment]
<img width="1169" alt="screen shot 2018-11-05 at 9 51 07 am" src="https://user-images.githubusercontent.com/26717697/48010089-885fa380-e0e2-11e8-8240-ba285aa5dcbe.png">
