### ISSUE TITLE
Hover and selected states need to look different

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#24]
“Server Health” tab should not be highlighted when page is currently on “Server Overview”. This is disorienting to user.

![screen shot 2018-10-12 at 2 09 25 pm](https://user-images.githubusercontent.com/4976631/46889191-744cbd00-ce28-11e8-91b0-9abe6a5ff002.png)

**Default state:** Dark blue background #1B2834, light grey for icon and text #E0E0E0
**Selected state:** White background #FFFFFF, Dark blue for icon and text #1B2834
**Hover state:** Grey background #DCDEE0, light blue for icon and text #3C6DF0

**Comment by ryanarnell** [comment]
Considering the second level navigation,  Alissa and I came up with this new color scheme. 
The hover state is white while selected state is grey. 

![screen shot 2018-10-16 at 4 12 11 pm](https://user-images.githubusercontent.com/4976631/47047884-7f705780-d15e-11e8-8546-b81a63787097.png)

**Comment by gtmills** [comment]
@ryanarnell @alissaylee I think the main and 2nd level navigation, should have the same hover color.

**Comment by alissaylee** [comment]
Let's have the hover states for main and secondary nav white, and the page that’s selected (i.e. Event log) can have the text be in bold with the > button visible.

**Comment by gtmills** [comment]
This was completed here: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/14275/

**Comment by ryanarnell** [comment]
This issue is resolved by this push - https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/14275/
