### ISSUE TITLE
Make actions visible in a disabled state

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#26]
**In event log page** 

Main actions should be made available via table header by default (currently it is hidden until checkbox is selected). Recommendation:

![screen shot 2018-10-12 at 2 27 10 pm](https://user-images.githubusercontent.com/4976631/46889958-f0e09b00-ce2a-11e8-86c2-f1a3e8dd2faa.png)

 Make actions visible in a disabled state so users understand features are associated with the table.

**Comment by gtmills** [comment]
With https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/15850/7/, 
I see:
<img width="559" alt="capture_eventlogs" src="https://user-images.githubusercontent.com/5455127/48637738-3cd7b000-e994-11e8-88c0-372b9a73e171.PNG">
Seems inconstant, "Mark as resolved" is readonly but Delete and export are not.

**Comment by ryanarnell** [comment]
Looks like we did not think about the empty scenario where there is no event log available.  A new issue is created with possible solution here https://github.com/openbmc/phosphor-webui/issues/44

**Comment by gtmills** [comment]
Tested out patch set 10 of https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/15850/: 
![patchset15850-10](https://user-images.githubusercontent.com/5455127/49393987-6284e900-f6f8-11e8-9b36-a68d48ce5010.PNG)
Formatting looks off on the table?

**Comment by ryanarnell** [comment]
The table had issues prior to this push. The way it is constructed with div elements, it will not response to wide range of data format. Here is a screenshot of **current** build.  (Not this code push but currently what is existing now )

![ss](https://user-images.githubusercontent.com/4976631/49398081-efcd3b00-f702-11e8-8816-172ffe37c7d0.jpg)
