### ISSUE TITLE
Help users recognize, diagnose, and recover from errors

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#27]
**In event log and summary page** 

Prioritize event logs by 1) severity level and then by   2) timestamp (top to bottom).

![screen shot 2018-10-12 at 2 31 13 pm](https://user-images.githubusercontent.com/4976631/46890151-811ee000-ce2b-11e8-8f7e-49e04e8eb661.png)

![screen shot 2018-10-12 at 2 32 05 pm](https://user-images.githubusercontent.com/4976631/46890192-9d228180-ce2b-11e8-88bc-13737f02c523.png)

**Comment by ryanarnell** [comment]
After user testing, we decided to keep the prioritizing by severity level. Thanks @gtmills  for bringing it up.

**Comment by gtmills** [comment]
Closing then. Thanks @ryanarnell
