### ISSUE TITLE
Fixed table header 

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#28]
Unable to understand context for all the temperature values when scrolling down the table. 

This pattern would apply to other pages that include tables. 

![screen shot 2018-10-12 at 2 39 55 pm](https://user-images.githubusercontent.com/4976631/46890511-b4ae3a00-ce2c-11e8-986d-40b8a284dd45.png)

 Recommendation: Table header stays fixed while user scrolls through table rows. Filter field and severity filter should also stay fixed due to its context to the table.

**Comment by BeccaBroek** [comment]
<img width="1275" alt="screen shot 2018-11-21 at 2 40 03 pm" src="https://user-images.githubusercontent.com/26717697/48867324-71d07200-ed9b-11e8-93c1-97aacb09b4bc.png">

Seeings some off spacing the spacing off for the word Sensors when I cherry picked

**Comment by ryanarnell** [comment]
![screen shot 2018-11-29 at 10 57 03 am](https://user-images.githubusercontent.com/4976631/49239701-043eca00-f3c9-11e8-856c-85e2fc2d9ff8.png)
