### ISSUE TITLE
Keep confirmation experience consistent

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#31]
1) Warning statement is not aligned with the action buttons, and does
2) Hover state color for buttons breaks accessibility standards.

![screen shot 2018-10-12 at 2 51 36 pm](https://user-images.githubusercontent.com/4976631/46891064-5aae7400-ce2e-11e8-9bc9-7bf51a29f386.png)

Keep confirmation experience consistent (like Firmware and Network settings pages) by having a modal pop up warning user about the implications of their action.

![screen shot 2018-10-12 at 2 54 30 pm](https://user-images.githubusercontent.com/4976631/46891208-bc6ede00-ce2e-11e8-909f-7a102db7dace.png)

**Comment by derick-montague** [comment]
@gtmills - Please close this ticket as we are working on a new design as part of boot options
