### ISSUE TITLE
Consistency and standards for In-memory firmware version

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#33]
Visual treatment of the “In-memory firmware version” implies a clickable state when in actuality it is not. This is in opposition to the same blue color treatment used in the UI as a call to action.

![screen shot 2018-10-12 at 3 13 27 pm](https://user-images.githubusercontent.com/4976631/46891974-6485a680-ce31-11e8-967d-e3a507e6a1bc.png)

Keep language consistent by referring to statement as “Functional firmware version:”
Recommendation: Use the color #666666 for the firmware version text, and change language to reflect “Functional firmware version:”.

**Comment by gtmills** [comment]
@ryanarnell I changed the text a few weeks ago and @BeccaBroek changed the color here already: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/13945/. Closing.
