### ISSUE TITLE
Firmware: Move upload/download to top and have radio button

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#34]
Layout of content is unclear that user can choose between two options to upload or download image files

![screen shot 2018-10-12 at 3 26 08 pm](https://user-images.githubusercontent.com/4976631/46892480-2be6cc80-ce33-11e8-8638-5ba32ccb4210.png)

Recommendation: Include the text “Or” between the two sections so user understands both are viable options (and not sequential inputs which is what it currently implies).

**Comment by gtmills** [comment]
@ryanarnell I thought @alissaylee had a decision where upload/download were a radio button? So only one would be visible.

**Comment by gtmills** [comment]
Tracking this with https://github.com/openbmc/phosphor-webui/issues/53
