### ISSUE TITLE
SNMP - Server Management

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#37]
[SNMP Settings prototype](https://ibm.invisionapp.com/share/RQNYHJ0VBDY#/318996535_1-_SNMP_Empty)

System Admins need to manage the connection to the SNMP server/s -- add, edit, remove, test connection.
* **Add manager button**: adds another set of fields for SNMP server (both manager server and port)
* **Manager Host Name or IP Address field**:  Format/syntax is validated while typing, connection to the server is tested using the Test button
    * Field validation error if the field is left empty:  'Field is required.'
    * Field validation error if the format is incorrect:  'Invalid format.'
* **Test button**: validates the Manager Host Name or IP Address connection only (not port field)
    * If the "Manager Host Name or IP Address" field shows the green checkmark indicating that was validated, then the Test button is disabled
    * If the  "Manager Host Name or IP Address" field is changed after successful validation, then is changed to a different value, then the Test button is enabled again
* **Port**:  Format/syntax is validated while typing, this field is not tested with the Test button 
    * Field validation error if the field is left empty:  'Field is required.'
    * Field validation error if the format is incorrect: 'Value should be between 0 and 65,535.'
* **Remove button**: removes the set of fields both manager server and port (the last set of fields cannot be removed)
* **Cancel button**: causes changes to not be saved
* **Save Settings button**: causes fields to be validated, and changes to be saved if there are no validation errors 
    * Manager server field validation error if there's a connection problem or invalid format
    * Port field validation error if the port's value isn't between 0 to 65,535.
    * Field validation error if either field is left empty while the other is filled in
    * If both fields are left empty and user saves settings, fields will not persist on the page.
    * Attempts to leave the page without saving edits will cause a confirmation message to appear stating changes will not be saved if the action continues
    * Toast notification appears when save is completed without validation errors
* **Validation instances**
    * Input field error states (before saving settings) are exclusive to format validity (e.g. port's value isn't between 0 to 65,535, character format)
    * Input field error states (after saving settings) will inform when there is a connection problem or IP address does not exist
    * Error Notifications: if error fields exist in the page upon saving settings (e.g. required fields are left empty, invalid IP address format)
* **Success Notifications** when settings were successfully saved

**Comment by gtmills** [comment]
New tab I assume under configuration, "SNMP settings".

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-snmp/blob/master/docs/snmp-configuration.md

**Comment by joseph-reynolds** [comment]
The description reads "System Admins need to ... test [the] connection [to the SNMP server]".
Later, it states, the "input field ...will inform when there is a connection problem."

However, the "Test" button description merely validates if the "Host Name" field has correct syntax.  And I found no interface to test the connection.  I would have thought the HostName field would validate itself by turning red or something if it contained incorrect data.  Then you don't need a test button.

**Comment by susantjasinski** [comment]
@joseph-reynolds The format/syntax of the "Manager Host Name or IP Address" field will be validated while typing.  The connection will be tested when the Test button is clicked. 

Remember, you are reviewing the future "ideal" design. The ability to perform these functions might not exist yet.

**Comment by BeccaBroek** [comment]
As far as "Manager Host Name or IP Address field: Format/syntax is validated while typing", @susantjasinski  I don't think we can validate the format of a hostname.

**Comment by BeccaBroek** [comment]
@jandraa could you update with new Invision design at some point?

**Comment by jandraa** [comment]
UPDATED InVision link: https://ibm.invisionapp.com/share/RQNYHJ0VBDY#/318996535_1-_SNMP_Empty
