### ISSUE TITLE
Power consumption is hard-coded to "000 W", must display actual data

### ISSUE THREAD

**Issue by AlexanderAmelkin** [openbmc/phosphor-webui#4]
Currently, both "Power Consumption" and "Power Cap" fields in "Power information" section of the Server overview page are hard-coded to "000 W".

**Comment by gtmills** [comment]
This is complete. https://github.com/openbmc/phosphor-webui/commit/3327583964a2b38bf2fd75f75d1d1f148f82f006 fixed this.
