### ISSUE TITLE
Move Style Guide to permanent location

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#41]
Style Guide is here: 
https://ibm.invisionapp.com/share/EBNYECMH3Y2#/screens

**Comment by gtmills** [comment]
Move to docs/ repo or keep in phosphor-webui?

**Comment by edtanous** [comment]
I vote docs repo, for a couple reasons.

1. it gets better visibility for both readership and reviews than the webui repo
2. It's under creative commons licence, which is a better fit for documentation like this.

We could bifurcate the license of the webui repo,  which would solve #2, but I still think that the docs repo is the best choice.

**Comment by susantjasinski** [comment]
The purpose of the guide is not to replace the bootstrap library. Instead, this guide will help front-end designers and developers provide consistent patterns, behaviors, and interactions such as colors, form and validation behaviors, accessibility interactions, terminology, animations, etc. 

Today, the style guide is shared as a series of flattened images (png). And the source files are not easily accessible to the community https://ibm.invisionapp.com/share/EBNYECMH3Y2.  

Building a website served through Github Pages would allow users to easily find and navigate to the information they need. It also allows users to interact with the content.

**Comment by edtanous** [comment]
The idea of github pages is interesting, but unless you're planning on moving all the existing documentation to that style (which I would fully support) we're bifurcating the documentation, which I really don't think helps us in the long run.  If you need to check in some documentation as HTML, so you can apply appropriate styles to it, that seems workable, as we can still make all the linking between markdown and html work.

**Comment by susantjasinski** [comment]
This open style guide version will be on hold until teams outside of IBM decide to engage with it. For the time being the IBM Design team will continue to document and share the GUI style guide as flat images in InVision.

**Comment by gtmills** [comment]
Closing. Will reopen if we decide to move somewhere.
