### ISSUE TITLE
overview does not work properly

### ISSUE THREAD

**Issue by nest1ing** [openbmc/phosphor-webui#42]
After the commit 569ccf66e58aacd50eaf53518c50c0ad4d448333 the `overview` page looks like this:
![default](https://user-images.githubusercontent.com/5609593/48551180-da27db00-e8e5-11e8-9f9e-8f9a4d693cf5.png)

As I find out, it happens because  in my case the value of `Date().toString()`   contains national characters in the time zone.
```javascript
new Date().toString()
"Thu Nov 15 2018 14:54:55 GMT+0300 (Москва, стандартное время)"
```

The events log page have the same behavior.

**Comment by nest1ing** [comment]
Maybe would better use `toUTCString()` / `toLocaleString()` instead parse the output of `toString()` to get the name of time zone?
In my case it looks like this:
```javascript
new Date().toUTCString()
"Thu, 15 Nov 2018 12:09:10 GMT"
new Date().toLocaleString()
"15.11.2018, 15:09:20"
```

But I am not sure how it may be implemented in the template parser. 
The template looks like this:
```
{{(tmz == 'UTC' ? (event.Timestamp | date:'medium': tmz) : (event.Timestamp | date:'medium')) + ' ' + tmz}}
```

**Comment by nest1ing** [comment]
Fix me if I wrong, but I believe that this code, even if it successfully parsed string, will give the time zone of the browser instead of the `BMC`:
```javascript
              // https://stackoverflow.com/questions/1091372/getting-the-clients-timezone-in-javascript
              // EDT (UTC - 04:00)
              $scope.bmc.timezone =
                  $scope.bmc.date.toString().match(/\(([A-Za-z\s].*)\)/)[1] +
                  ' ' + createOffset($scope.bmc.date);
```
same for the `host`:
```javascript
              $scope.host.timezone =
                  $scope.host.date.toString().match(/([A-Z]+[\+-][0-9]+.*)/)[1];
```

**Comment by gtmills** [comment]
Cherry picked https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/15894/2/
Without 15894/2/ :
<img width="197" alt="before_15894" src="https://user-images.githubusercontent.com/5455127/48638623-c7211380-e996-11e8-9b45-53b18970835d.PNG">
<img width="560" alt="before_15894-2" src="https://user-images.githubusercontent.com/5455127/48638625-c8524080-e996-11e8-9d99-2231a2c9b5b1.PNG">
With 15894/2/ :

<img width="548" alt="with_15894" src="https://user-images.githubusercontent.com/5455127/48638654-dacc7a00-e996-11e8-86fd-485ac1e1e6d5.PNG">
<img width="231" alt="with_15894-2" src="https://user-images.githubusercontent.com/5455127/48638658-dc963d80-e996-11e8-9d6d-318f5334b7d4.PNG">

**Comment by nest1ing** [comment]
I've fixed it.

And @gtmills, @BeccaBroek: I want to get your attention to the my previous question.
As I understood, in this case we want to use the time zone of the user's browser.
I specially leave both of these methods (see [app/configuration/controllers/date-time-controller.js](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/15894/3/app/configuration/controllers/date-time-controller.js)), but I believe we should use only one of them.

**Comment by AlexanderAmelkin** [comment]
Speaking of formats I would go with YYYY/MM/DD for date, a standard timezone abbreviation (e.g. PST, CST, MSK, GMT, etc.) that every admin around the world is used to, and the time in locale-specific format (e.g. "11:59 PM" or "23:59").

Indeed, everybody always gets confused over mm/dd and dd/mm in formats with trailing yyyy, but there is just a single format with year first, and that is YYYY/MM/DD. Correct me if I'm wrong, but I've never seen YYYY/DD/MM used anywhere by anyone. Thus, if we put year first, we give user a hint that it is the month that follows and is followed by the day.

Any verbose natural language name for time zone poses a risk of not fitting into visual design, and of breaking language grammar rules. That may be not obvious for people speaking case-less languages like English where nouns never change, but for languages like Russian it makes a big difference grammar-wise whether you say "Екатеринбургское время" (nominative case) or "Екатеринбургского времени" (genitive case) or "Екатеринбургскому времени" (prepositional case), and the required case differs based on context. Hence, writing "YEKT" or "MSK" or "CST" is much safer.

Representation of time though doesn't suffer from any of those problems and hence can safely use locale settings. Moreover, it is totally unacceptable to use 'am/pm' notation for at least Russia and all the ex-USSR countries, as nobody here gets the concept of 12:00pm following 11:59am. and as far as I'm aware, US citizens are also uncomfortable with 24h time format calling it 'military' (I would also be uncomfortable if I pronounced it in hundreds). Hence the proposal to use locale settings for this part.

**Comment by nest1ing** [comment]
It is the reason of the opening this issue.
The browser with Russian locale give `Thu Nov 15 2018 14:54:55 GMT+0300 (Москва, стандартное время)` instead the awaited `Thu Nov 15 2018 14:54:55 GMT+0300 (MSK)`. And I was unable to find any methods to get `MSK` without external dependencies.

**Comment by AlexanderAmelkin** [comment]
It appears that timezone support is crippled in ECMAscript and differs from browser to browser.
The only compatible method I could find is using [moment-timezone.js](http://momentjs.com/timezone/).
This code gives me 'MSK' in any browser using any browser l18n and with any system locale, provided that my computer is indeed in MSK timezone:

```
<script src="http://momentjs.com/downloads/moment-with-locales.min.js" language="Javascript"></script>
<script src="http://momentjs.com/downloads/moment-timezone-with-data-2012-2022.min.js" language="Javascript"></script>
...
function getUserTimezone(date) {
        const ro = Intl.DateTimeFormat().resolvedOptions();
        return moment.tz(date, ro.timeZone).format('z');
}
```
I guess we could add momentjs to phosphor-webui. It would take extra 76KB though.

**Comment by BeccaBroek** [comment]
I also was looking into moment-timezone.js at one point because it would make managing date/time across browsers a lot more simple, but thought I had come up with a solution that avoided the extra 76KB (but clearly my commit is breaking these pages in certain timezones). I do have a branch locally from when I was working on this in which I had brought in moment-timezone that I could push up for review if the 76KB is not a concern. @gtmills @edtanous, any thoughts on bringing this library into the GUI?

**Comment by gtmills** [comment]
@AlexanderAmelkin Where does this 76KB  for momentjs come from? Is this 76KB compressed ?

**Comment by gtmills** [comment]
I would prefer not bringing in momentjs  but if it is needed, I understand.

**Comment by nest1ing** [comment]
> Alternatively, has anyone considered just fixing the regex that's causing the issue?

Yes, it was first what I tried.
But it gives the name of the time zone in Russian and it looks strange.

**Comment by AlexanderAmelkin** [comment]
@edtanous, yes it's 76k compressed when bundled "with data" and "with locales" as in my example above. The code itself is quite small.

Fixing regexp doesn't work because it will capture "Москва, стандартное время" instead of "MSK"  if Firefox has Russian localization installed. The only solution I was able to find that would always give "MSK" (not "Europe/Moscow", not "Москва, стандартное время", not "GMT+3:00", etc.) regardless of user's browser settings was momentjs. I realize and agree that bringing in 76k of compressed and minified javascript is a bit of overkill for just this task, but I couldn't find anything better. There is no standard API for that, unfortunately.

**Comment by nest1ing** [comment]
In my opinion, we may accept that the browser doesn't know the abbreviation of the Moscow time zone and it will be shown as `GMT+3`:
![default](https://user-images.githubusercontent.com/5609593/49228829-3c600000-f3fd-11e8-9940-1fab7d706f76.png)

But there still is one strange thing: at data/time settings page it looks like this:
![default](https://user-images.githubusercontent.com/5609593/49228678-ee4afc80-f3fc-11e8-80bc-bfced5216bda.png)

**Comment by nest1ing** [comment]
> I guess we could add momentjs to phosphor-webui. It would take extra 76KB though.

> If we drop locales support ... then it will be like 41k compressed.

I guess you tried non minified versions and/or compression with default level.
I download it, then run `gzip -9` and now it looks like this:
```shell
$ ls -l 
total 32
-rw-rw-r-- 1 shurik shurik 16755 Oct 29 06:13 moment.min.js.gz
-rw-rw-r-- 1 shurik shurik  9177 Oct 29 06:13 moment-timezone-with-data-2012-2022.min.js.gz
```

**Comment by gtmills** [comment]
@nest1ing That seems more reasonable for a size.

**Comment by AlexanderAmelkin** [comment]
@gtmills, good. Then let's do it.
Let's draw the bottom line:

1. Import minified momentjs without locales support as we only need it for en-based timezone abbreviations
2. Import minified moment-timezone with data 2012-2022
3. Change dates format to: '<YYYY/MM/DD> <locale-based time format> <en-locale-based timezone abbreviation>', e.g. `2018/11/30 15:27 MSK` or `2018/11/30 6:27 AM CST`.

As I said before, I believe the YYYY/MM/DD format is the most compact, language-neutral, unambiguous and text sorting friendly. Time must be represented in locale-specific way because nobody outside the English-speaking world understands the AM/PM format, and the English-speaking world doesn't like the 24-hour format.

**Comment by gtmills** [comment]
The IBM design team is not a fan of `YYYY/MM/DD`. One comment was "spelling out the month is helpful and how it's done on a lot of modern UIs". @susantjasinski Can weigh in more here. 
It appears the [angularjs date filter](https://docs.angularjs.org/api/ng/filter/date) does not work as it should. Sorry for leading us down that path. I see PM posted in the [example above](https://user-images.githubusercontent.com/5609593/49228829-3c600000-f3fd-11e8-9940-1fab7d706f76.png) (I believe this is incorrect for the locale).

Any way we can still make toLocaleTimeString() work? 
What about this:
```
var event = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = { year: 'numeric', month: 'short', day: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', timeZoneName: 'short' };

// British English output: "19 Dec 2012, 21:00:00 GMT-6"
console.log(event.toLocaleString('en-GB', options ));

//United Statues English output: "Dec 19, 2012, 9:00:00 PM CST"
console.log(event.toLocaleString('en-US', options));

// Arabic output:  ٩:٠٠:٠٠ م غرينتش-٦" 
console.log(event.toLocaleString('ar-EG', options));

// German(Germany) output: "19. Dez. 2012, 21:00:00 GMT-6"
console.log(event.toLocaleString('de-DE', options));

// Russian output: "19 дек. 2012 г., 21:00:00 GMT-6"
console.log(event.toLocaleString('RU', options));
```
The timezone would still display as `GMT +/- x`. Is that okay? 
The date/time would be in the locale language is that okay? 

The actual code would look like: 
```
var ro = Intl.DateTimeFormat().resolvedOptions();
var options = { year: 'numeric', month: 'short', day: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', timeZoneName: 'short' };
console.log(event.toLocaleString(ro.lang, options ));
```

**Comment by edtanous** [comment]
All of the compression information above has been presented so far are based on either grabbing the pre-minified versions of the library, or gzipping things manually.  Given that we already have infrastructure to minify and gzip as part of the build process, I would like to see numbers from the current build process (preferably in the form of a patch submitted to gerrit) before we pass judgement on whether or not the size increase is acceptable.  Said another way, I care about how big it is as deployed in the current environment.  All other measurements (manually minifying, manually gzipping, pre-minified, xz compressed) are unimportant to this discussion.

If we want to change how the minification and compression works, that is another topic of discussion, and should be had in a different issue, don't think anyone is advocating for that.

@AlexanderAmelkin 
For #1 above.  We will not import the minified version.  We will use the minification infrastructure that exists in the build already, as it allows selectable debug builds, doesn't check in any libraries directly, and makes us more immune to the minification injection attacks that seem to be plaguing npm as of late.
#2 Agree, the time limited package seems like the best bet.  Most of the systems we're working on will be long out of support window by the time 2022 rolls around.

@nest1ing: "looks strange" is much better than a crash.  While I agree, it's not perfect, I think we should fix the regex anyway just to get the UI working for Russian Locales, then work to come up with a "best" solution as we figure out the minification and size issues on momentjs.

@gtmills "spelling out the month is helpful and how it's done on a lot of modern UIs"
My opinion here isn't very strong in either direction.  With numbers, I like the ability find the duration between event times quickly, on the other hand, spelling out the month is easier to read if looking in the context of a single event.  I"m fine with whatever solution you guys come up with.

**Comment by nest1ing** [comment]
@edtanous: You are right, when `momentjs` was installed by the `npm install` command it increased used space for around 75K, and I agree - it is too many.

**Comment by AlexanderAmelkin** [comment]
@BeccaBroek, can you check how much space does momentjs occupy for you in the final image being brought in without pre-minification as @edtanous suggested. Our quick check gave us 75k which is very strange provided we got just about 25k from the pre-minified and manually compressed versions.

**Comment by gtmills** [comment]
I had a few comments on https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/15894/ but why not go with that patch instead of adding momentjs ?
