### ISSUE TITLE
GUI: SSL Certificate management page

### ISSUE THREAD

**Issue by jandraa** [openbmc/phosphor-webui#43]
A user can manage their certificates (CA certificates, client certificates, and server certificates). Users should be able to see the uploaded file (and upload a new one if wanted), the start date, and expiration date.

**Comment by gtmills** [comment]
Need a new page for uploading an SSL Certificate

**Comment by jandraa** [comment]
_From Alissa:_

Work in progress...
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318902299_SSL_Certification
SSL certificate upload management page

Support/upload file types...
More than one CA file (work in progress)
Single server certificate file
Choose and upload file(s)
Remove loaded file
See if file(s) successfully uploaded
Remove existing file(s)
CA - signed certificate only, server + client certificates (private key + signed certificate)
Expose to user that private key data needs to be included in certificate file upon upload (private key + signed certificate)
Outstanding questions/decisions that need to be made:

Is the client certificate upload specific to LDAP? - YES, and this function will exist in the LDAP page #177
Is client certificate an optional or required field? - YES, #177
Can we expose expiration dates for certificates? (still a WIP, will be clearer in 1-2 weeks; can this data be extracted from front-end vs back-end?)
Can we support generating CSR-based certificates?
Are CSR-based certificates specific only to server certificates?
Future requirements to consider

Blacklist (disable) certificate files
Show user when certificate is reaching expiration date (e.g. notification, exposing via server overview page)
Possibility that generating certificate experience could co-exist with certificate upload management page #182

**Comment by jandraa** [comment]
- [ ] Verify all three certificate types are designed; add to necessary panels
- [ ] Conduct user research to determine where in the navigation SSL certificates should live
- [ ] Conduct user research to determine where client certificates should live (LDAP vs. SSL certification) 
- [ ] Update upload component so it can scale to multi-file upload scenarios
- [ ] Consider where and how users should be notified of expired certificates
