### ISSUE TITLE
Event log: update screens where there are no event logs available

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#44]
When there is no event log available these 3 changes need to be made in the current design- 
1. The checkbox in table header should be disabled
2. The action buttons will be in disable state 
3. A message should display in the content area saying "There are no event logs". We are determining the actual verbiage of the message. 

Here is a screenshot 

<img width="898" alt="screen shot 2018-11-20 at 11 54 59 am" src="https://user-images.githubusercontent.com/4976631/48793296-21ceae00-ecbc-11e8-9cf3-1a81fbcd0fb1.png">

**Comment by susantjasinski** [comment]
I don't understand the phrase "# Events are Logged". I think this shows the number of events that display based on a search or filter? In this case, should it read "Results" instead?

**Comment by susantjasinski** [comment]
"There are no Event Logs" is not correct. Change to "No events have been found for this log."

**Comment by BeccaBroek** [comment]
User messages:
If no logs at all - 'No events have been logged yet.'
If there are logs but the filters return none - 'There are no events that match the selected criteria.'
