### ISSUE TITLE
Log In notifications

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#47]
[Log In Notifications - InVision Mockups](https://ibm.invisionapp.com/share/B9NYI6RMDJQ#/318935058_Login_Default)

System Admins should be able to understand issues that occur while attempting to log into the BMC web ui.

**Comment by gtmills** [comment]
Why would we display a message that says "Note: LDAP is enabled, and local accounts are disabled?"

**Comment by susantjasinski** [comment]
@gtmills If I recall correctly, this was supposed to inform the person logging in whether they were to use the LDAP or local account login credentials. If you didn't understand it, then perhaps we need to readdress how we are doing that.

**Comment by susantjasinski** [comment]
Customer feedback: one customer expressed concern with letting users know whether LDAP is enabled or not, stating it could be a security concern.

**Comment by edtanous** [comment]
Can you give quantify better what the security concern is?  We’re currently mocking up the admin console, which requires an active login before anything is disclosed.  Given that admins have the ability to check the enabled state of ldap (and even change it) anyway via the ldap page, why would a notification be a concern?

**Comment by susantjasinski** [comment]
@edtanous Are you suggesting that we can't display that LDAP is enabled or not until they have already logged in? If this is true, then we can't show the message anyway.

**Comment by edtanous** [comment]
I didn't realize this was intended to be pre-login.  Per the security architecture, we can't release any system specific information until the user is authenticated and authorized.  This is relatively standard for embedded web server implementations.  Even today, we're already exposing too much to un-logged in users through the static files, which allows fingerprinting OpenBMC.  That's on the list to fix with a static form based, no-javascript login page.

**Comment by gtmills** [comment]
I agree with Ed, it should say "Invalid username or password" regardless of if LDAP is enabled. Also, we should not say "Note: LDAP is enabled, and local accounts are disabled?" on the bottom of the page.

**Comment by susantjasinski** [comment]
Ok, thank you for the feedback. The IBM team had a similar sentiment, but we were still trying to figure out how to make it work. Looks like it would be best NOT to include. 

I updated the design mockups.

**Comment by gtmills** [comment]
![login](https://user-images.githubusercontent.com/5455127/50114807-27f87180-020b-11e9-8469-75f81ea136a1.PNG)
The error in one is a popup, the error in the other, the text appears under the field.

**Comment by susantjasinski** [comment]
@BeccaBroek 
- I removed 'invalid format' message from the mockups.
- yes, all other messages (invalid user name and password, server is unreachable, field is required) would appear after the user clicks the 'Log in' button

@gtmills we realize the inconsistency, but having a single message when the ID or password is invalid is a standard used widely in UIs, so we thought it was best to stick with that best practice.

And as a reminder to everyone, I've removed references to LDAP enablement on this panel

**Comment by susantjasinski** [comment]
Max Cooper:  AMI BMC does not have this field. OpenBMC gives: Server unreachable if another Server IP was used

Richard: What is the purpose of this IP address. We will connect to BMC through ip address (say https:// right). Why do we need this specifically?

Reply:  
Providing the hostname on this panel allows users to log into a different BMC ... the first-attempt solution for multi-server control. This field is populated by default with the BMC hostname or IP address that was most recently logged into -- and gives the user affordance where they will be logged into and if there was a problem logging in

**Comment by susantjasinski** [comment]
Gunnar Mills: So currently with our CSRF prevention we don't allow logging into another machine from a different machine's GUI so I think we should revisit this.

@gtmills Lets revisit this. Thank you all for your input

**Comment by frsauvage** [comment]
Hi @gtmills ,

>  CSRF prevention we don't allow logging into another machine from a different machine's GUI so I think we should revisit this.

Do you know if it is now possible to log on from a different machine' GUI ?

Because I try and it does not work 
$http does NOT allow me from another machine.

Regards,
Francine

**Comment by gtmills** [comment]
Hi @frsauvage , 

> 
> Do you know if it is now possible to log on from a different machine' GUI ?
> 
Not without turning off XSS and CSRF PREVENTION in bmcweb and some changes to Content Security Policy: "default-src 'self'". 
https://github.com/openbmc/bmcweb/blob/1bfbe0e0372de7991bab9bb0a7ba015356f7d3b2/CMakeLists.txt#L46
