### ISSUE TITLE
User Account Management and notifications

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#48]
[Management User Accounts - InVision Mockups](https://ibm.invisionapp.com/share/B9NYI6RMDJQ#/318975108_1_Users_Empty)

System Admin should be able to manage the users that can locally access the host/BMC in a way that is consistent with the rest of the GUI.

**Comment by jandraa** [comment]
New designs created by Intel and pushed to the build. 

These designs, however, do not follow the design patterns followed by other panels (LDAP in particular, since it is the most related) so there needs to be an effort to to take another pass at the current designs on the build.

**Comment by jandraa** [comment]
Updated design suggestions by IBM : https://ibm.invisionapp.com/share/RQNYHJ0VBDY  

Open question: 
1. Are user ID’s needed? 
2. Does ‘unlocking’ a user require a password reset?
3. Who has access to this panel? 

Need user feedback and community feedback.

**Comment by gtmills** [comment]
@jandraa Is this the latest user management design?

**Comment by jandraa** [comment]
This is the latest https://ibm.invisionapp.com/share/4XNZ0JAMJ7B#/319147576_6-4-1_Regular

**Comment by gtmills** [comment]
Done.
