### ISSUE TITLE
Event Filter does not filter on event type, only on content

### ISSUE THREAD

**Issue by AlexanderAmelkin** [openbmc/phosphor-webui#5]
As can be seen in the attached screenshots, event filter only filters by event content, but not by event type:

![Filtering by type](https://user-images.githubusercontent.com/4518124/41608992-73a90290-73f2-11e8-8034-6b241c1087ce.png)
![Filtering by content](https://user-images.githubusercontent.com/4518124/41608993-73d3af72-73f2-11e8-8d7c-75b6b0b62206.png)

**Comment by AlexanderAmelkin** [comment]
AFAIK, PSU events don't exist in upstream openbmc, but this issue applies to all event types, not just PSUs. Those screenshots are just for illustration, you can try any event that is available in your event log to reproduce this issue.

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-webui/blob/d27bb135f1561b87a174d1b9890dde2f3cf01c80/app/common/directives/log-search-control.js#L32 is the code that does the search I believe

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/11347/ is the fix

**Comment by AlexanderAmelkin** [comment]
Thanks. Will check it out.
