### ISSUE TITLE
GUI power operation pop up is off the visual range

### ISSUE THREAD

**Issue by gkeishin** [openbmc/phosphor-webui#51]
In latest public master build, the Power operation pop up is really off than usual 

![image](https://user-images.githubusercontent.com/19584499/49522105-df68bc00-f8cc-11e8-9edb-d8f3a8fa36b6.png)

**Comment by gtmills** [comment]
Without https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/16191/
![16191-without](https://user-images.githubusercontent.com/5455127/50119146-73b11800-0217-11e9-922c-0d039d9d8dea.PNG)

With https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/16191/ 
![16191-with](https://user-images.githubusercontent.com/5455127/50119168-81ff3400-0217-11e9-8a8e-36ec8bed91d7.PNG)
