### ISSUE TITLE
IP KVM

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#52]
[IPKVM - InVision Mockups](https://ibm.invisionapp.com/share/B9NYI6RMDJQ#/318953777_IP_KVM)

This panel is being designed to be consistent with the Serial over LAN (SoL) panel which also has a console. 2 customers stated that they like the console embedded in the panel, but also want the capability to open the console in a popup window - same as the SoL panel design.

The console window size should respond to the changing size of the window it is viewed in; e.g. as the window gets taller, the console should grow taller as well.

**Comment by gtmills** [comment]
This is complete.
