### ISSUE TITLE
Firmware Updates

### ISSUE THREAD

**Issue by susantjasinski** [openbmc/phosphor-webui#53]
System Admins need to load firmware images onto the BMC so that they can update their firmware.

This change moves the upload and download options to the top of the panel so that it is visible when the user first opens the panel. It is also simplified for an easier user experience that takes up less screen real estate.

**Upload image file from workstation**

* **Upload image file from workstation radio button**  allows the user to upload a firmware image file from a workstation or laptop
* **Choose file button** opens a default browser window. The user will not be restricted on file type. 
     * After the file is chosen, the text next to the button changes to “Loading files”, and the file’s name displays in a field below the button and a progress icon animates
     * When loading completes, the progress icon changes to a close “x” icon and the text next to the button changes to “1 file detected”
     * Clicking the close “x” icon removes/unloads the file
* **Upload firmware button** causes the file to upload to the BMC 
     * After the button is clicked, the file field changes to a progress bar with the text “Upload in progress”, and the text next to the button changes to “1 file is uploading…”
     * If the upload fails, the field appears as a validation error (red outline and embedded help), and a toast notification appears identifying the error
     * If the upload is successful, then the panel changes to its default and a toast notification appears identifying the success

**Upload image file from workstation**

* **Download image file from TFTP server radio button**  allows the user to download a firmware image file from a TFTP server
* **TFTP server IP address field** is required, and is validated for format while typing
* **File name field** is required
* **Test IP address button** validates the connection to the TFTP server. Failure causes validation error to appear, success causes the success icon to appear. This is informational only, a failed connection will not hinder the user from clicking the Download firmware button
* **Download firmware button** causes the file to be downloaded to the BMC 
     * After the button is clicked, a progress bar appears below the fields with the text “Download in progress”
     * If the upload fails due to a timeout, the validation error (red line and embedded help) appears below the fields, and a toast notification appears identifying the error
     * If the upload fails due to a connection issue, the IP address field appears as a validation error (red outline and embedded help), and a toast notification appears identifying the error
     * If the upload is successful, then the panel changes to its default and a toast notification appears identifying the success

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-webui/issues/34 looks like the same issue.

**Comment by jandraa** [comment]
Most recent design: https://ibm.invisionapp.com/share/RQNYHJ0VBDY#/319006100_V2-1-_Firmware

**Comment by derick-montague** [comment]
This design is out of date. Will be creating a new story to address the updated design.
