### ISSUE TITLE
The delete button on the new manage user accounts is hide

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#57]
![delete_button_not_showing](https://user-images.githubusercontent.com/5455127/50781336-ba1ff280-126a-11e9-9082-d788b5259ec7.PNG)

**Comment by gtmills** [comment]
@apuli1 I am testing with the newest master,  v2.4-235-g16be88d. What browser are you using? I see this problem on firefox and edge. On chrome, the "Delete" button is visible but the right side corners are not rounded like the other corners. 
![chrome](https://user-images.githubusercontent.com/5455127/50841461-6b399200-132a-11e9-97c3-a9a026119186.PNG)

**Comment by BeccaBroek** [comment]
Using in chrome, I'm also seeing some strange styling on the dropdown menu. The rounded edges and the arrow is cut off on the right side of input.
<img width="427" alt="screen shot 2019-01-14 at 10 40 24 am" src="https://user-images.githubusercontent.com/26717697/51126512-f6ae9980-17e8-11e9-8268-9fb516495b5a.png">

This is in chrome, but I think just removing the bootstrap 'form-control' class on the input solves ->>

<img width="870" alt="screen shot 2019-01-14 at 10 39 57 am" src="https://user-images.githubusercontent.com/26717697/51126580-22318400-17e9-11e9-97bb-afd69d65b401.png">

Made comment in gerrit as well.

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17116/ should have fixed
