### ISSUE TITLE
Blank error shown even when user is successfully added

### ISSUE THREAD

**Issue by gtmills** [openbmc/phosphor-webui#58]
Filled in information for a new user:
![before-save](https://user-images.githubusercontent.com/5455127/50781584-5944ea00-126b-11e9-8554-fbe7b4ec899d.PNG)
Hit save:
![after-save](https://user-images.githubusercontent.com/5455127/50781588-5b0ead80-126b-11e9-8d00-6a4e8ca9a495.PNG)
You can see the new user in the table above but a blank error is still shown.

**Comment by gtmills** [comment]
Also, have a problem where if the user is not successfully created, not seeing the proper error
Before save:
![before_save_fail](https://user-images.githubusercontent.com/5455127/50781910-323ae800-126c-11e9-880e-4674a2b60874.PNG)
After save:
![after_save_fail](https://user-images.githubusercontent.com/5455127/50781919-35ce6f00-126c-11e9-86ed-9df525ec8102.PNG)
User failed to be created (no new user in the table)

**Comment by apuli1** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17116/
