### ISSUE TITLE
GUI Serial over LAN (SoL) window doesnt stream the boot progress

### ISSUE THREAD

**Issue by gkeishin** [openbmc/phosphor-webui#59]
In the latest Master yacto2.6 build https://openpower.xyz/job/openbmc-build/1911/

the GUI SOL page doesn't stream the boot progress messages. The port 2200 is working though.

**Comment by gtmills** [comment]
Confirmed this on a master build. See `websocket closed. code: 1005 reason: ` in the console.

**Comment by gtmills** [comment]
Works with a build with https://github.com/openbmc/openbmc/commit/16be88d944049ebc52e0d5f07cf2b8be750c54e1

**Comment by gtmills** [comment]
I believe https://github.com/openbmc/openbmc/commit/768c645a0e038166ee3e46441f5b5a4fe6c9b891 caused this and https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/16913/  should fix this

**Comment by gkeishin** [comment]
This is now working on latest build

```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.6.0.rc1-23"
VERSION_ID="2.6.0.rc1-23-g5a2b44f"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.6.0.rc1-23"
BUILD_ID="2.6.0.rc1"
root@witherspoon:~# 
```
