### ISSUE TITLE
Feature list for SP Next

### ISSUE THREAD

**Issue by ryanarnell** [openbmc/phosphor-webui#63]
We are comparing our existing OpenBMC GUI built with ASMi systems and trying to come up with a feature list that we will be able to present in front of users for testing and rearrangement. We are asking steak-holders and ASMI feature experts to get a better understating of the feature lists. 
The link for this is https://ibm.ent.box.com/file/358077213839 

Based on this we are constructing a more consolidated list which can be found in - 
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Navigation%20Structure.xml#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1Hy2FbFbvSnruafHshHABujage4apyG36%26export%3Ddownload

**Comment by gtmills** [comment]
This is IBM specific. It has a link to an IBM box and uses internal IBM code names. Closing.
