### ISSUE TITLE
Secondary button hover is not accessible

### ISSUE THREAD

**Issue by derick-montague** [openbmc/phosphor-webui#66]
## File
`app/common/styles/base/buttons.scss`
**Line: 58 - 63**
```
 &:hover {
    background: $lightbg__accent;
    cursor: pointer;
    background: $secbtn__bg;
    @include fastTransition-all;
  }
```

## Issue
- [ ] There are two declarations in the CSS rule with the `.btn-secondary:hover` selector. Remove  the following declaration`background: $lightbg__accent`

- [ ] Add a color to override the `#fff` that bootstrap sets. Should use `$secbtn__text`

### As Is
![image](https://user-images.githubusercontent.com/1183515/52091377-d6693380-2579-11e9-9ea5-348b77a9140c.png)

### To Be
![image](https://user-images.githubusercontent.com/1183515/52091588-8343b080-257a-11e9-84f0-b70008e4bb8a.png)

**Comment by BeccaBroek** [comment]
@derick-montague 

can you elaborate on "There are two declarations in the CSS rule with the .btn-secondary:hover selector. Remove the following declarationbackground: $lightbg__accent" ?
