### ISSUE TITLE
Filter button is not aligned correctly

### ISSUE THREAD

**Issue by derick-montague** [openbmc/phosphor-webui#67]
## File
`app/common/styles/elements/content-search.scss`
**Line: 49**

## Issue
The filter button in the text fields are not property aligned. It is too large for the field.

### As Is
![image](https://user-images.githubusercontent.com/1183515/52092271-9b1c3400-257c-11e9-8be5-71e8c2ad3d9e.png)

![image](https://user-images.githubusercontent.com/1183515/52092303-bedf7a00-257c-11e9-9d83-2a2247c3ba06.png)

### To Be
![image](https://user-images.githubusercontent.com/1183515/52092513-652b7f80-257d-11e9-8740-c552240e53f9.png)
![image](https://user-images.githubusercontent.com/1183515/52092539-7a081300-257d-11e9-8ac0-f2b2988a9bfc.png)

**Comment by derick-montague** [comment]
I am not seeing this in master only in one of the patches being reviewed. 

WebUI: Adding Filters support to SEL logs: `17024`

**Comment by gtmills** [comment]
![filter-event-log](https://user-images.githubusercontent.com/5455127/61738948-0b985680-ad51-11e9-8f5f-4a181a5e5e3f.PNG)
Current master. @derick-montague Do we ned more work here?

**Comment by derick-montague** [comment]
No, we can close this.
