### ISSUE TITLE
Colors not accessible - selected category in side-nav

### ISSUE THREAD

**Issue by jandraa** [openbmc/phosphor-webui#70]
On the selected state, the color of the icon is not accessible. Please chance from Blue 40 to Blue 50. 

Reference in Style Guide: 
Colors: https://ibm.invisionapp.com/d/#/console/15339466/318902254/preview
Side Navigation: https://ibm.invisionapp.com/d/#/console/15339466/318902250/preview

** Note that Blue40 had to change from #3C6DF0 to #2D60E5 to be accessible. Additionally, Red50 changed from #E62325 to #DA1416 for the same reason.

Currently on the Build: 
<img width="119" alt="Screen Shot 2019-03-19 at 2 16 54 PM" src="https://user-images.githubusercontent.com/44675611/54635216-ab677000-4a51-11e9-9b54-ef4f6f731132.png">

**Comment by derick-montague** [comment]
This change to blue will resolve more than just this contrast issue. We are using that blue as a link color and so many buttons and links don't meet WCAG AA contrast guidelines of 4.5:1 ratio. I am updating this and this fix alone increases our Accessibility score a fair bit in Lighthouse on the Server Overview page.

**Comment by derick-montague** [comment]
@gtmills Can you assign this to me and update the status?
