### ISSUE TITLE
'Edit' host name doesn't apply saved changes when the name contains a space

### ISSUE THREAD

**Issue by jandraa** [openbmc/phosphor-webui#71]
On the server overview page, when the 'Edit' button is clicked to change the host name, there are two problems:
1) The saved host name should be pre-populated in the field, where the user can modify and give a new name.

--> The current name of the host should be displayed in the field. As soon as the user starts typing, the original name should be replaced by what the user is entering. 

2) If the user includes a space in the new name, there is no error presented and a user is able to successfully save. However, the new name is not applied. Furthermore, when the user clicks 'Edit' again, this time the field is pre-populated with the new name that was just entered.
Ex. If I change the name from 'witherspoon' to 'witherspoon 2', I will still see 'witherspoon'. Then, if I click 'edit' again, I will see 'witherspoon 2' in the text field. 

--> If no spaces are allowed, that should be stated in the popup, the field should validate for it, and the user should not be able to save. 
--> If spaces are allowed, the new name should be displayed after the save.

**Comment by derick-montague** [comment]
@gtmills - This issue has a review in Gerrit pending and should be in current sprint and assigned to @dixsie

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/20669
Disabled button on code drop ^

![Screen Shot 2019-05-01 at 11 23 02 AM](https://user-images.githubusercontent.com/8097306/57029023-379ab480-6c06-11e9-863b-b7d9025b1ad7.png)

**Comment by dixsie** [comment]
Primary disabled button colors per style guide

<img width="602" alt="Screen Shot 2019-05-03 at 10 20 09 AM" src="https://user-images.githubusercontent.com/26472611/57147488-49f32a80-6d8d-11e9-8d46-856b6cb0a344.png">
<img width="750" alt="Screen Shot 2019-05-03 at 10 19 55 AM" src="https://user-images.githubusercontent.com/26472611/57147489-49f32a80-6d8d-11e9-9255-3247fc3886e9.png">
