### ISSUE TITLE
Code upload failed on BMC web UI 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/phosphor-webui#77]
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.7.0-dev"
VERSION_ID="2.7.0-dev-255-g58f1b4b"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.7.0-dev"
BUILD_ID="2.7.0-dev"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~#

```

Downloaded BMC image, and try doing code update via BMC web UI in firmware section. The upload progress status shows it progressed but when page is refresh the new image is not loaded on the BMC  /tmp/images/

**Comment by gtmills** [comment]
@gkeishin This sounds like a problem with the backend code update, not a GUI problem. Anything in the journal?

**Comment by gkeishin** [comment]
I dont see anything on journald.. so that kind of weird. The back end is still intact and the CI running the back end code update, so we looked good there.

**Comment by gkeishin** [comment]
Still persistent failure on latest master too.. @gtmills can we try to root cause this one.. Thanks

**Comment by BeccaBroek** [comment]
<img width="529" alt="Screen Shot 2019-04-10 at 1 58 59 PM" src="https://user-images.githubusercontent.com/26717697/55906662-6808a900-5b9a-11e9-8a82-2718a80e49ac.png">

![image](https://user-images.githubusercontent.com/26717697/55906731-8c648580-5b9a-11e9-9949-e3dea0cb85e8.png)


The following console errors needed to be resolved - we were using an inline onClick that isn't supported by newer browsers, and also the click-outside directive implemented in https://github.com/openbmc/phosphor-webui/commit/84e7a936db2addc3c10be97c3b348b9ffdb3601b 
was throwing the top error. With both of these errors resolved, George was able to upload firmware images as expected.
