### ISSUE TITLE
Activate image and reboot BMC is not rebooting the BMC

### ISSUE THREAD

**Issue by BeccaBroek** [openbmc/phosphor-webui#79]
![Screen Shot 2019-04-10 at 11 26 45 AM](https://user-images.githubusercontent.com/26717697/55896330-ad6dac00-5b83-11e9-9c90-b972f48c45d8.png)

Recreate:
1. upload BMC image
2. click activate
3. see popup and choose 'activate and reboot'
4. You will see the image activate, but the BMC will not reboot.

**Comment by derick-montague** [comment]
@gtmills - Is this currently being worked on?
